apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-channel-grow
  namespace: __namespace__
  labels:
    app: bot-channel-grow
    git-commit: commit_placeholder
spec:
  selector:
    matchLabels:
      app: bot-channel-grow
  template:
    metadata:
      labels:
        app: bot-channel-grow
        git-commit: commit_placeholder
    spec:
      containers:
      - name: main
        image: registry.digitalocean.com/wbsnail/bots:__tag__
        ports:
        - containerPort: 9527
        env:
        - name: ENV
          value: __env__
        command:
        - /bots
        args:
        - serve
        - channel-grow
        - -c
        - /opt/config/config.yaml
        volumeMounts:
        - name: config
          mountPath: /opt/config
      volumes:
      - name: config
        configMap:
          name: bot-channel-grow
      imagePullSecrets:
      - name: digitalocean-wbsnail
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-banana-manager
  namespace: __namespace__
  labels:
    app: bot-banana-manager
    git-commit: commit_placeholder
spec:
  selector:
    matchLabels:
      app: bot-banana-manager
  template:
    metadata:
      labels:
        app: bot-banana-manager
        git-commit: commit_placeholder
    spec:
      containers:
      - name: main
        image: registry.digitalocean.com/wbsnail/bots:__tag__
        ports:
        - containerPort: 9527
        env:
        - name: ENV
          value: __env__
        command:
        - /bots
        args:
        - serve
        - banana-manager
        - -c
        - /opt/config/config.yaml
        volumeMounts:
        - name: config
          mountPath: /opt/config
      volumes:
      - name: config
        configMap:
          name: bot-banana-manager
      imagePullSecrets:
      - name: digitalocean-wbsnail
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-wbsnail
  namespace: __namespace__
  labels:
    app: bot-wbsnail
    git-commit: commit_placeholder
spec:
  selector:
    matchLabels:
      app: bot-wbsnail
  template:
    metadata:
      labels:
        app: bot-wbsnail
        git-commit: commit_placeholder
    spec:
      containers:
      - name: main
        image: registry.digitalocean.com/wbsnail/bots:__tag__
        ports:
        - containerPort: 9527
        env:
        - name: ENV
          value: __env__
        command:
        - /bots
        args:
        - serve
        - wbsnail
        - -c
        - /opt/config/config.yaml
        volumeMounts:
        - name: config
          mountPath: /opt/config
      volumes:
      - name: config
        configMap:
          name: bot-wbsnail
      imagePullSecrets:
      - name: digitalocean-wbsnail
